### ISSUE TITLE
After 2-factor authentication, forward results in a 404 "/_oauth/authorize" not found

### ISSUE THREAD

**Issue by martinskrodzki** [eduvpn/python-eduvpn-client#539]
# Installation

Following the [installation guide for Ubuntu 22.04](https://python-eduvpn-client.readthedocs.io/en/master/installation.html#ubuntu-22-04).

# Version

4.1.1
no update available

# Check if your issue is in the known issues list

Issue unknown

# OS/Distribution

Ubuntu 22.04 LTS

# Logs

## Do you have a problem while adding before connecting?

I fire up EduVPN and tell it to connect to TU Delft, here's the debug log:

`2023-08-25 09:20:33,215 - MainThread - DEBUG - eduvpn.ui.app - app.py:70 - activate
2023-08-25 09:20:33,342 - <function ApplicationModelTransitions.get_previous_servers at 0x7fe9ce4652d0> - DEBUG - eduvpn.app - app.py:37 - Transition: NO_SERVER, old state: DEREGISTERED
2023-08-25 09:20:35,610 - MainThread - DEBUG - eduvpn.ui.ui - ui.py:989 - activated server: <eduvpn_common.server.InstituteServer object at 0x7fe9cda8b220>
2023-08-25 09:20:35,613 - <function ApplicationModelTransitions.loading_server at 0x7fe9ce465510> - DEBUG - eduvpn.app - app.py:61 - Transition: LOADING_SERVER, old state: NO_SERVER
2023-08-25 09:20:35,614 - <function ApplicationModelTransitions.chosen_server at 0x7fe9ce4656c0> - DEBUG - eduvpn.app - app.py:66 - Transition: CHOSEN_SERVER, old state: LOADING_SERVER
2023/08/25 09:20:35 - Go - DEBUG - Getting access token
2023/08/25 09:20:35 - Go - DEBUG - Got a refresh token error: failed obtaining HTTP resource: https://tudelft.eduvpn.nl/portal/oauth.php/token as it gave an unsuccessful status code: 400. Body: {"error":"invalid_grant"}
2023-08-25 09:20:35,659 - <function ApplicationModelTransitions.start_oauth at 0x7fe9ce465f30> - DEBUG - eduvpn.app - app.py:91 - Transition: OAUTH_STARTED, old state: CHOSEN_SERVER
2023-08-25 09:20:35,660 - open-browser - DEBUG - eduvpn.app - app.py:107 - Opening web browser with url: https://tudelft.eduvpn.nl/portal/_oauth/authorize?client_id=org.eduvpn.app.linux&code_challenge=cXfxAj35qhqWRmWmpg6SOCVXvCgPYFpmmH-tOBQBBpk&code_challenge_method=S256&redirect_uri=http%3A%2F%2F127.0.0.1%3A41971%2Fcallback&response_type=code&scope=config&state=6CQ_8ZLTc6HHMYrQFlSScbVsCIiF0KKQutHpB9s4JIs
2023-08-25 09:20:36,049 - open-browser - DEBUG - eduvpn.app - app.py:111 - Running os.wait for browser
2023-08-25 09:20:36,050 - open-browser - DEBUG - eduvpn.app - app.py:116 - Done waiting for browser
`
In the browser, I can log in to TU Delft and authenticate with my second factor. Then, I'm being forwarded to

`https://tudelft.eduvpn.nl/portal/_oauth/authorize?client_id=org.eduvpn.app.linux&code_challenge=cXfxAj35qhqWRmWmpg6SOCVXvCgPYFpmmH-tOBQBBpk&code_challenge_method=S256&redirect_uri=http%3A%2F%2F127.0.0.1%3A41971%2Fcallback&response_type=code&scope=config&state=6CQ_8ZLTc6HHMYrQFlSScbVsCIiF0KKQutHpB9s4JIs`

where it says 404 "/_oauth/authorize" not found. Manually correcting the link above by removing the underscore before "oauth" gets me to a page where I can approve the application. If I do so, it says "Authorization Failed". The debug console now reads:

`2023-08-25 09:26:40,392 - <function ApplicationModelTransitions.get_previous_servers at 0x7fe9ce4652d0> - DEBUG - eduvpn.app - app.py:37 - Transition: NO_SERVER, old state: OAUTH_STARTED
2023-08-25 09:26:40,393 - <function ApplicationModelTransitions.get_previous_servers at 0x7fe9ce4652d0> - DEBUG - eduvpn.app - app.py:37 - Transition: NO_SERVER, old state: NO_SERVER
2023/08/25 09:26:40 - Go - DEBUG - Running token callback
2023-08-25 09:26:40,394 - <function ApplicationModelTransitions.get_previous_servers at 0x7fe9ce4652d0> - DEBUG - eduvpn.app - app.py:37 - Transition: NO_SERVER, old state: NO_SERVER
2023-08-25 09:26:40,395 - call-model - DEBUG - eduvpn.app - app.py:340 - Save tokens called
2023-08-25 09:26:40,395 - call-model - WARNING - eduvpn.app - app.py:342 - Got empty tokens, not saving them to the keyring
2023/08/25 09:26:40 - Go - ERROR - failed obtaining HTTP resource: https://tudelft.eduvpn.nl/portal/oauth.php/token as it gave an unsuccessful status code: 400. Body: {"error":"invalid_grant"} 
with stacktrace: *http.StatusError failed obtaining HTTP resource: https://tudelft.eduvpn.nl/portal/oauth.php/token as it gave an unsuccessful status code: 400. Body: {"error":"invalid_grant"}
/build/python3-eduvpn-common-MhvSBv/python3-eduvpn-common-1.1.0/internal/http/http.go:225 (0x7fe9cd589078)
/build/python3-eduvpn-common-MhvSBv/python3-eduvpn-common-1.1.0/internal/http/http.go:164 (0x7fe9cd5ef3e5)
/build/python3-eduvpn-common-MhvSBv/python3-eduvpn-common-1.1.0/internal/oauth/oauth.go:248 (0x7fe9cd5ef3ad)
/build/python3-eduvpn-common-MhvSBv/python3-eduvpn-common-1.1.0/internal/oauth/oauth.go:405 (0x7fe9cd5f020c)
/build/python3-eduvpn-common-MhvSBv/python3-eduvpn-common-1.1.0/internal/oauth/oauth.go:412 (0x7fe9cd5f0273)
/build/python3-eduvpn-common-MhvSBv/python3-eduvpn-common-1.1.0/internal/oauth/oauth.go:168 (0x7fe9cd5eea69)
/usr/lib/go-1.18/src/sync/once.go:68 (0x7fe9cd31b1c2)
/usr/lib/go-1.18/src/sync/once.go:59 (0x7fe9cd5eea0b)
/build/python3-eduvpn-common-MhvSBv/python3-eduvpn-common-1.1.0/internal/oauth/oauth.go:167 (0x7fe9cd5ee9c7)
/usr/lib/go-1.18/src/net/http/server.go:2084 (0x7fe9cd55f28f)
/usr/lib/go-1.18/src/net/http/server.go:2462 (0x7fe9cd560c29)
/usr/lib/go-1.18/src/net/http/server.go:2916 (0x7fe9cd56287b)
/usr/lib/go-1.18/src/net/http/server.go:1966 (0x7fe9cd55dd37)
/usr/lib/go-1.18/src/runtime/asm_amd64.s:1571 (0x7fe9cd316121)`

And the GUI says: 
`The following error was reported: failed obtaining HTTP resource: https://tudelft.eduvpn.nl/portal/oauth.php/token as it gave an unsuccessful status code: 400. Body: {"error":"invalid_grant"}.`

If find the same information as given by the debug in `home/martin/.config/eduvpn/log`

**Comment by ttsmit** [comment]
I am facing the same issue since yesterday, with the same errors. Running the same version, installed via AUR. I also tried to remove the underscore, but that was failing as well.

**Comment by martinskrodzki** [comment]
What worked for me was:

1. Open the GUI.
2. Right-Click on the server.
3. "Remove Server".
4. Add the server again.

Now, I can connect just fine. Seems like an update of the software broke the stored connection.

**Comment by jwijenbergh** [comment]
Thanks for the issue, I looked at the code and I can confirm that I am not correctly updating the authorization and token endpoints used for OAuth when they're refreshed from the server. Will be fixed in the next release

**Comment by jwijenbergh** [comment]
Fixed in the latest, update your system

**Comment by akhmerov** [comment]
I still see this error in freshly updated 4.1.2 on Ubuntu 23.04.

**Comment by jwijenbergh** [comment]
> I still see this error in freshly updated 4.1.2 on Ubuntu 23.04.

When do you see it? When you click on the server or?

**Comment by akhmerov** [comment]
I see 1.1.0 in python shell. 4.1.2 is reported in the GUI info.

![image](https://github.com/eduvpn/python-eduvpn-client/assets/2069677/204e37a0-766f-48aa-8a51-5b49bfb9615f)

**Comment by akhmerov** [comment]
Ah, just upgraded again and everything works. Thanks!

**Comment by jwijenbergh** [comment]
Cool!

**Comment by irm-codebase** [comment]
@jwijenbergh 
Just to report that I am facing the same issue in version 4.1.3 Re-adding my institution fixed it.

Not sure if the fix is meant to be invisible to users... so I thought mentioning it might be important.

**Comment by jwijenbergh** [comment]
The fix should be invisible. When you get a configuration we now obtain the new endpoints first. Note that it can fail if the server returns an error when the endpoints are fetched. Could you share a log?

**Comment by irm-codebase** [comment]
Ahhh, then that might be the issue. There is a mismatch: I have 1.1.1.

`eduVPN GUI version: 4.1.3 with eduvpn-common version: 1.1.0`

I am running Linux Mint 21.2.

**Comment by jwijenbergh** [comment]
Do you have a version with pip and apt at the same time? Did you run `sudo apt upgrade`?
